### /api/auth/signup endpoint - Register a new user

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "fullName": "Iuri Goncalves",
    "email": "a32192@alunos.ipca.pt",
    "password": "lameira15"
}

### /api/auth/login - Login an existing user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "lameira15"
}

### /api/auth/logout - Logout a user

POST http://localhost:3000/api/auth/logout

### /api/auth/check - Check if a user is authenticated

GET http://localhost:3000/api/auth/check


