### /api/auth/signup endpoint - Register a new user

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "johndoe@gmail.com",
    "password": "1234567"
}

### /api/auth/login - Login an existing user

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "1234567"
}

### /api/auth/logout - Logout a user

POST http://localhost:3000/api/auth/logout

### /api/auth/check - Check if a user is authenticated

GET http://localhost:3000/api/auth/check


### /api/messages/contacts - Fetch contacts

GET http://localhost:3000/api/messages/contacts


### /api/messages/send/:id - Send a message

POST http://localhost:3000/api/messages/send/68e8c7c5d93b36a41a03431
Content-Type: application/json

{
    "text": "Eu mesmo"
}

### /api/messages/:id - Get Messages by user id

GET http://localhost:3000/api/messages/68e8c58aed5d198066ff0433

### /api/messages/chats - Fetch a user's chats

GET http://localhost:3000/api/messages/chats

